@startuml

title __ENTITIES's Class Diagram__\n

  namespace entities {
    class entities.BasicTask {
        - completionDate : LocalDateTime
        - description : String
        - entryDate : LocalDateTime
        - id : int
        + BasicTask()
        + BasicTask()
        + completionTimeFromCustom()
        + completionTimeFromSet()
        + getCompletion()
        + getDescription()
        + getEntry()
        + getId()
        + getPriority()
        + isCompleted()
        + setCompletion()
        + setDescription()
        + setEntry()
        + setId()
        + setPriority()
        + toString()
        - compareLocalDateTime()
        - timeDiffToString()
    }
  }
  

  namespace entities {
    interface entities.DAO {
        {abstract} + add()
        {abstract} + edit()
        {abstract} + get()
        {abstract} + remove()
    }
  }
  

  namespace entities {
    enum Priority {
      high
      low
      medium
    }
  }
  

  namespace entities {
    interface entities.Task {
        {abstract} + completionTimeFromCustom()
        {abstract} + completionTimeFromSet()
        {abstract} + getCompletion()
        {abstract} + getDescription()
        {abstract} + getEntry()
        {abstract} + getId()
        {abstract} + getPriority()
        {abstract} + isCompleted()
        {abstract} + setCompletion()
        {abstract} + setDescription()
        {abstract} + setEntry()
        {abstract} + setId()
        {abstract} + setPriority()
    }
  }
  

  namespace entities {
    class entities.User {
        - email : String
        - id : int
        - password : String
        - username : String
        + getEmail()
        + getId()
        + getPassword()
        + getUsername()
        - User()
    }
  }
  

  namespace entities {
    class entities.User.UserBuilder {
        - email : String
        - id : int
        - password : String
        - username : String
        + UserBuilder()
        + build()
        + withEmail()
        + withId()
        - mask()
    }
  }
  

  entities.BasicTask .up.|> entities.Task
  entities.BasicTask o-- entities.Priority : priority
  entities.User +-down- entities.User.UserBuilder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
